### ISSUE TITLE
Make a fluent builder class, to handle all custom HTTP Handlers that the client may have

### ISSUE THREAD

**Issue by DanielCauser** [TorontoMobileDevelopers/HttpTracer#2]
https://www.codeproject.com/Articles/640997/Fluent-interfaces-and-Method-Chaining-in-Csharp

**Comment by ChaseFlorell** [comment]
What do you foresee the API looking like for this? What's the purpose of a fluent API on this lib?

_man, I always feel like my terse questions make me sound like an asshole, but I genuinely want to know.. if for no other reason than that I'd like to submit a PR_

**Comment by DanielCauser** [comment]
Hahaha, I want to have this builder available, in case the user has other Custom Handlers of his own. We have to make sure that our HttpTracerHandler is the "Root" handler, and all other custom handlers, are chained in the InnerHandler of our Tracer handler.

**Comment by ChaseFlorell** [comment]
How does that work? What's the purpose of multiple handlers?

**Comment by dylanberry** [comment]
That doesn't work if one of the handlers is adding a gzip header/handler.

**Comment by DanielCauser** [comment]
I thought that we could chain the httphandlers that users might have together, make sure our handler would be the root, so we would be sure that the user could have other handlers and also have ours. But after testing it out, it seems that I was wrong on how the handlers behave. @dylanberry is completely right. This will not work. I'm closing this issue o/

**Comment by DanielCauser** [comment]
aaaand we are bringing this back ahahaha.
